#!/usr/bin/env node
/**
 * Generate src/generated/routes.ts + namespaces.ts from openapi/tool-routes.registry.mjs
 *
 * Source of truth in the private monorepo:
 *   docs/openapi/tool-routes.registry.mjs  (copied via npm run sync)
 */
import fs from "fs";
import path from "path";
import { fileURLToPath, pathToFileURL } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SDK_ROOT = path.join(__dirname, "..");
const REGISTRY = path.join(SDK_ROOT, "openapi", "tool-routes.registry.mjs");
const OUT_DIR = path.join(SDK_ROOT, "src", "generated");

/** OpenAPI tag → SDK namespace (stable public grouping). */
const TAG_TO_NAMESPACE = {
  "SEO Tools": "seo",
  "SEO APIs": "seo",
  "Security APIs": "security",
  "Text Utilities": "text",
  Convertors: "convertors",
  Documents: "documents",
  Office: "office",
  Web: "web",
  eBook: "ebook",
  Archive: "archive",
  "File Extract": "extract",
  Calculators: "calculators",
  "Unit Conversions": "units",
  "YouTube Tools": "youtube",
  "Text Intelligence": "textIntelligence",
  "AI Models": "ai",
  "Developer APIs": "developer",
};

function toMethodName(operationId) {
  if (!operationId.includes("_")) return operationId;
  return operationId
    .split("_")
    .map((part, i) =>
      i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join("");
}

/** @param {import('../../openapi/tool-routes.registry.mjs').toolGroups} toolGroups */
function flattenOperations(toolGroups) {
  /** @type {Array<{operationId:string,method:string,path:string,tag:string,namespace:string,multipart?:boolean,fileField?:string,jsonBody?:boolean,noAuth?:boolean,queryParams?:string[],responseFormat?:string}>} */
  const ops = [];

  for (const group of toolGroups) {
    const namespace = TAG_TO_NAMESPACE[group.tag] ?? "other";

    if (group.slugPost && group.slugs) {
      for (const slug of group.slugs) {
        const operationId = slug.replace(/-/g, "_");
        ops.push({
          operationId,
          method: "POST",
          path: `${group.basePath}/${slug}`,
          tag: group.tag,
          namespace,
          jsonBody: true,
          responseFormat: "nodeEnvelope",
        });
      }
    }

    if (group.routes) {
      for (const route of group.routes) {
        if (route.operationId?.endsWith("SupportedConversions")) continue;
        /** @type {string[]} */
        const queryParams = (route.queryParams ?? [])
          .map((p) => p.name)
          .filter((n) => n !== "delivery" && n !== "format");

        ops.push({
          operationId: route.operationId,
          method: route.method.toUpperCase(),
          path: `${group.basePath}${route.path}`,
          tag: group.tag,
          namespace,
          multipart: route.multipart,
          fileField: route.fileField ?? (route.multipart ? "file" : undefined),
          jsonBody: route.jsonBody,
          noAuth: route.noAuth,
          queryParams: queryParams.length ? queryParams : undefined,
          responseFormat: route.responseFormat,
        });
      }
    }
  }

  const byId = new Map();
  for (const op of ops) {
    if (byId.has(op.operationId)) {
      console.warn(`WARN duplicate operationId: ${op.operationId}`);
    }
    byId.set(op.operationId, op);
  }
  return [...byId.values()].sort((a, b) => a.operationId.localeCompare(b.operationId));
}

function emitRoutesModule(operations) {
  const lines = [
    "/** AUTO-GENERATED by scripts/generate-sdk.mjs — do not edit */",
    "export type HttpMethod = \"GET\" | \"POST\" | \"PUT\" | \"PATCH\" | \"DELETE\";",
    "",
    "export interface OperationDefinition {",
    "  operationId: string;",
    "  method: HttpMethod;",
    "  path: string;",
    "  tag: string;",
    "  namespace: string;",
    "  multipart?: boolean;",
    "  fileField?: string;",
    "  jsonBody?: boolean;",
    "  noAuth?: boolean;",
    "  queryParams?: string[];",
    "  responseFormat?: string;",
    "}",
    "",
    "export const OPERATIONS = {",
  ];

  for (const op of operations) {
    lines.push(`  ${JSON.stringify(op.operationId)}: ${JSON.stringify(op, null, 2).replace(/\n/g, "\n  ")},`);
  }

  lines.push("} as const satisfies Record<string, OperationDefinition>;");
  lines.push("");
  lines.push("export type OperationId = keyof typeof OPERATIONS;");
  lines.push(`export const OPERATION_COUNT = ${operations.length};`);
  lines.push("");
  lines.push("export const NAMESPACES = [");
  const ns = [...new Set(operations.map((o) => o.namespace))].sort();
  for (const n of ns) lines.push(`  ${JSON.stringify(n)},`);
  lines.push("] as const;");
  lines.push("export type Namespace = (typeof NAMESPACES)[number];");

  return `${lines.join("\n")}\n`;
}

function emitNamespacesModule(operations) {
  /** @type {Map<string, typeof operations>} */
  const byNs = new Map();
  for (const op of operations) {
    if (!byNs.has(op.namespace)) byNs.set(op.namespace, []);
    byNs.get(op.namespace).push(op);
  }

  const lines = [
    "/** AUTO-GENERATED by scripts/generate-sdk.mjs — do not edit */",
    "import type { OperationId } from \"./routes.js\";",
    "",
    "export interface NamespaceMethod {",
    "  operationId: OperationId;",
    "  methodName: string;",
    "}",
    "",
    "export const NAMESPACE_METHODS: Record<string, NamespaceMethod[]> = {",
  ];

  for (const [ns, ops] of [...byNs.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${JSON.stringify(ns)}: [`);
    for (const op of ops.sort((a, b) => a.operationId.localeCompare(b.operationId))) {
      const methodName = toMethodName(op.operationId);
      lines.push(
        `    { operationId: ${JSON.stringify(op.operationId)}, methodName: ${JSON.stringify(methodName)} },`
      );
    }
    lines.push("  ],");
  }

  lines.push("};");
  lines.push("");
  lines.push("/** operationId → camelCase method name */");
  lines.push("export const METHOD_NAME_BY_OPERATION: Record<OperationId, string> = {");
  for (const op of operations) {
    lines.push(
      `  ${JSON.stringify(op.operationId)}: ${JSON.stringify(toMethodName(op.operationId))},`
    );
  }
  lines.push("} as Record<OperationId, string>;");

  return `${lines.join("\n")}\n`;
}

function emitMcpMetadataModule() {
  const skillsPath = path.join(SDK_ROOT, "openapi", "mcp-skills.json");
  const workflowsPath = path.join(SDK_ROOT, "openapi", "mcp-workflows.json");

  /** @type {{ skills: Array<{ id: string, title: string, category: string, description: string, operationIds: string[] }> }} */
  const skillsPayload = fs.existsSync(skillsPath)
    ? JSON.parse(fs.readFileSync(skillsPath, "utf8"))
    : { skills: [] };

  /** @type {{ workflows: Array<{ id: string, title: string, description: string, synthesizer?: string, steps: Array<{ id: string, operationId: string }> }> }} */
  const workflowsPayload = fs.existsSync(workflowsPath)
    ? JSON.parse(fs.readFileSync(workflowsPath, "utf8"))
    : { workflows: [] };

  const lines = [
    "/** AUTO-GENERATED by scripts/generate-sdk.mjs — do not edit */",
    "",
    "export interface McpSkillMeta {",
    "  id: string;",
    "  title: string;",
    "  category: string;",
    "  description: string;",
    "  operationIds: string[];",
    "}",
    "",
    "export interface McpWorkflowStepMeta {",
    "  id: string;",
    "  operationId: string;",
    "  continueOnError?: boolean;",
    "  inputFrom?: string;",
    "}",
    "",
    "export interface McpWorkflowMeta {",
    "  id: string;",
    "  title: string;",
    "  description: string;",
    "  synthesizer?: string;",
    "  steps: McpWorkflowStepMeta[];",
    "}",
    "",
    `export const MCP_SKILLS: McpSkillMeta[] = ${JSON.stringify(skillsPayload.skills ?? [], null, 2)};`,
    "",
    `export const MCP_WORKFLOWS: McpWorkflowMeta[] = ${JSON.stringify(
      (workflowsPayload.workflows ?? []).map((w) => ({
        id: w.id,
        title: w.title,
        description: w.description,
        ...(w.synthesizer ? { synthesizer: w.synthesizer } : {}),
        steps: w.steps ?? [],
      })),
      null,
      2
    )};`,
    "",
  ];

  return `${lines.join("\n")}\n`;
}

async function main() {
  if (!fs.existsSync(REGISTRY)) {
    console.error(`Registry missing: ${REGISTRY}\nRun: npm run sync`);
    process.exit(1);
  }

  const { toolGroups } = await import(pathToFileURL(REGISTRY).href);
  const operations = flattenOperations(toolGroups);

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, "routes.ts"), emitRoutesModule(operations));
  fs.writeFileSync(path.join(OUT_DIR, "namespaces.ts"), emitNamespacesModule(operations));
  fs.writeFileSync(path.join(OUT_DIR, "mcp-metadata.ts"), emitMcpMetadataModule());

  console.log(`Generated ${operations.length} operations → src/generated/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
